# Generated by Django 2.2 on 2019-04-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xiaoqu', models.CharField(blank=True, max_length=255, null=True)),
                ('dlou_id', models.CharField(db_column='Dlou_id', max_length=10)),
                ('dno_id', models.CharField(db_column='Dno_id', max_length=10, unique=True)),
                ('dws', models.CharField(db_column='Dws', max_length=10)),
            ],
            options={
                'db_table': 'health',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('n_tag', models.CharField(db_column='N_tag', max_length=255, primary_key=True, serialize=False)),
                ('n_time', models.DateTimeField(blank=True, db_column='N_time', null=True)),
                ('n_content', models.CharField(blank=True, db_column='N_content', max_length=255, null=True)),
            ],
            options={
                'db_table': 'notice',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlou_id', models.CharField(db_column='Dlou_id', max_length=10)),
                ('dno_id', models.CharField(db_column='Dno_id', max_length=10)),
                ('dwx', models.CharField(db_column='Dwx', max_length=100)),
                ('dsun', models.CharField(db_column='Dsun', max_length=255)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uno', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('xiaoqu', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(max_length=225)),
                ('usex', models.CharField(blank=True, max_length=4, null=True)),
                ('password', models.CharField(blank=True, max_length=225, null=True)),
                ('ulou', models.CharField(blank=True, max_length=225, null=True)),
                ('uln', models.CharField(blank=True, max_length=225, null=True)),
                ('uphone', models.CharField(blank=True, max_length=255, null=True)),
                ('flag', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlou_id', models.CharField(db_column='Dlou_id', max_length=10)),
                ('xiaoqu', models.CharField(blank=True, max_length=225, null=True)),
                ('dno_id', models.CharField(db_column='Dno_id', max_length=10)),
                ('wwt', models.CharField(blank=True, db_column='Wwt', max_length=10, null=True)),
                ('wdt', models.CharField(blank=True, db_column='Wdt', max_length=10, null=True)),
            ],
            options={
                'db_table': 'water',
            },
        ),
    ]
