# Generated by Django 2.2 on 2019-04-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password1',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
